# for your convenience
DEBUG_CONFIG_KEY_ALIAS="key0"
DEBUG_CONFIG_KEY_PASSWORD="yobayoba"
DEBUG_CONFIG_STORE_PASSWORD="yobayoba"
DEBUG_CONFIG_FILEPATH="keys/debugConfig"
DEBUG_SERVER_URL=http://10.0.47.10:3000
RELEASE_SERVER_URL=http://140.82.37.38:3000