# for your convenience
DEBUG_SERVER_URL=http://10.0.47.10:3000/api/v1/
RELEASE_CONFIG_KEY_ALIAS="key0"
RELEASE_CONFIG_KEY_PASSWORD="yobayoba"
RELEASE_CONFIG_STORE_PASSWORD="yobayoba"
RELEASE_CONFIG_FILEPATH="keys/ReleaseKey"
RELEASE_SERVER_URL=http://140.82.37.38:3000/api/v1/