#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Sat Jan 26 14:05:56 YEKT 2019
# suppress inspection "UnusedProperty"
apiSecret=84e6f247bc1ac6b7a39f919733665b0e5f471ca3057d821b324d96583561ebd3
